[build]
  command = "npm run build && npm run build:functions"
  publish = "dist"
  functions = ".netlify/functions-build"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["stripe"]

[[redirects]]
  from = "/netlify/functions/*"
  to = "/netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  publish = "dist"
  autoLaunch = true